#!/bin/bash

scriptDir="$(dirname "$0")"

projectName=$1

if [[ $projectName == "" ]]
then
  echo "No project dir specified!"
  exit 1
fi

projectPath="$scriptDir/$projectName"
if [ -d $projectPath ]
then
  echo "Project Directory $projectPath not empty!"
  exit 1
fi

echo "Creating Project Named $projectName"

mkdir -p $projectPath
mkdir -p $projectPath/src

pathToScript="$(realpath --relative-to=$projectPath $scriptDir)"
ln -s $pathToScript/build $projectPath/build
