#!/bin/bash

scriptDir="$(dirname "$0")"

srcPath="${scriptDir}/src"
binPath="${scriptDir}"
executeableName="main"

executeablePath="$binPath/$executeableName"

if [ ! -d $srcPath ]
then
  echo "No src directory found!"
  exit 1
fi

if [ ! -d "$binPath" ]
then
  mkdir $binPath
fi

if [ -f "$executeablePath" ]
then
  rm $executeablePath
fi

gcc -o $executeablePath $srcPath/*.c -lm
$executeablePath
